
package tp.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FileUploaderImplService", targetNamespace = "http://service.tp/", wsdlLocation = "http://localhost:8080/wsCalculateur/services/uploadWs?wsdl")
public class FileUploaderImplService
    extends Service
{

    private final static URL FILEUPLOADERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException FILEUPLOADERIMPLSERVICE_EXCEPTION;
    private final static QName FILEUPLOADERIMPLSERVICE_QNAME = new QName("http://service.tp/", "FileUploaderImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/wsCalculateur/services/uploadWs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FILEUPLOADERIMPLSERVICE_WSDL_LOCATION = url;
        FILEUPLOADERIMPLSERVICE_EXCEPTION = e;
    }

    public FileUploaderImplService() {
        super(__getWsdlLocation(), FILEUPLOADERIMPLSERVICE_QNAME);
    }

    public FileUploaderImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FILEUPLOADERIMPLSERVICE_QNAME, features);
    }

    public FileUploaderImplService(URL wsdlLocation) {
        super(wsdlLocation, FILEUPLOADERIMPLSERVICE_QNAME);
    }

    public FileUploaderImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FILEUPLOADERIMPLSERVICE_QNAME, features);
    }

    public FileUploaderImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileUploaderImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FileUploader
     */
    @WebEndpoint(name = "FileUploaderImplPort")
    public FileUploader getFileUploaderImplPort() {
        return super.getPort(new QName("http://service.tp/", "FileUploaderImplPort"), FileUploader.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FileUploader
     */
    @WebEndpoint(name = "FileUploaderImplPort")
    public FileUploader getFileUploaderImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.tp/", "FileUploaderImplPort"), FileUploader.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FILEUPLOADERIMPLSERVICE_EXCEPTION!= null) {
            throw FILEUPLOADERIMPLSERVICE_EXCEPTION;
        }
        return FILEUPLOADERIMPLSERVICE_WSDL_LOCATION;
    }

}
