
package tp.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FileUploader", targetNamespace = "http://service.tp/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FileUploader {


    /**
     * 
     * @param fileToUpload
     */
    @WebMethod
    @RequestWrapper(localName = "uploadFile", targetNamespace = "http://service.tp/", className = "tp.service.UploadFile")
    @ResponseWrapper(localName = "uploadFileResponse", targetNamespace = "http://service.tp/", className = "tp.service.UploadFileResponse")
    public void uploadFile(
        @WebParam(name = "fileToUpload", targetNamespace = "")
        FileToUpload fileToUpload);

}
